import turtle
turtle.speed(0)
turtle.title("Richard's turtle")
turtle.setup(425,425,0,0)
turtle.pencolor('red')
turtle.fillcolor('purple')
turtle.begin_fill()
turtle.width(10)
turtle.circle(100)
turtle.end_fill()
turtle.pencolor('pink')
turtle.fillcolor('pink')
turtle.penup()
turtle.left(90)
turtle.fd(50)
turtle.rt(90)
turtle.begin_fill()
turtle.circle(50)
turtle.end_fill()
turtle.goto(0,-5)
turtle.pendown()
turtle.pencolor('green')
turtle.rt(90)
turtle.fd(250)
turtle.fillcolor('green')
turtle.goto(0,-125)
turtle.rt(90)
turtle.pencolor('green')
turtle.begin_fill()
turtle.goto(-70,-50)
turtle.goto(70,-50)
turtle.goto(0,-125)
turtle.end_fill()
turtle.pencolor('black')
turtle.write("Richard",align="left", font=("Comic Sans MS", 9, "normal"))
turtle.hideturtle()
